### ISSUE TITLE
Allow prefix-less script filenames in /bp

### ISSUE THREAD

**Issue by foolishswish** [bluelhf/BytePaper#1]
Instead of constantly using the command " bp load uff.bsk" in console, perhaps change it to automatically make it add .bsk if it is not defined as .bsk .

for example if you type  " bp load uff" and dont specify the .bsk , that it does it by default then 

Thank you.

**Comment by bluelhf** [comment]
Great idea :)

**Comment by BaeFell** [comment]
I like this idea too. Replicating some of Skript's good behaviour would be a good thing to do going forward. This would make it easier for users to migrate if BytePaper becomes a good replacement.

**Comment by bluelhf** [comment]
I have some local changes at home that would make implementing this drastically easier. I should have access to them by July, but they'll have to be merged properly.

**Comment by bluelhf** [comment]
**Commit a1544f0ff8ef8659f439dd7b7f1cd7a08aa7b23b** is the latest compiling commit, and should (in theory) **resolve this issue**.

**Extra testing is needed** to confirm whether the desired functionality is present, after which this issue can be closed. The artifact for the aforementioned commit is available via [Nightly Link](https://nightly.link/bluelhf/BytePaper/actions/runs/2658562967/BytePaper%20Nightly%20Artifact.zip).

**Comment by bluelhf** [comment]
# Supported in [v0.3.0](https://github.com/bluelhf/BytePaper/releases/tag/v0.3.0) :)
