### ISSUE TITLE
Updates to the development cycle and branch management

### ISSUE THREAD

**Issue by bluelhf** [bluelhf/BytePaper#2]
## In its current state, BytePaper's development cycle is primitive and difficult.
BytePaper is slowly growing out of being a single-contributor hobbyist project, and as such, it may soon be time to consider changes to the project's development cycle, particularly how releases and branches are handled. It is the goal of this issue to spark such discussion, and, if possible, choose and track the implementation process of a solution.

### Status quo

As it stands, BytePaper only contains one branch, `main`, which is contributed to directly. This does not allow for testing outside the local repository before changes are finalised, and causes a need for messy revert commits directly in production code. Single-branch development usually works fine for single-contributor, zero-user test projects, but becomes rather troublesome when multiple people are involved. A different system will be, if it is not already, needed.

### Alternatives
There are two main possibilities for the future of the development cycle in BytePaper: one is a dev-pending-release cycle, and the other is continuous development. In the dev-pending-release cycle, features are added to a branch, `dev`, then, prior to each release, quality assurance and complex testing is done on a separate `release-pending` branch, after which the main branch, called `release`, is fast-forwarded to `release-pending` (and a new release is made). In continuous development, code is packaged into many small high-quality changes, representing individual units of work which function independently of one another. These commits are pushed as a kind of "stream" — instead of multiple releases, the only relevant version of the code is the most recent one. This has its benefits, but also limits quality assurance and testing, and forces thinking of development as single, independent blocks, which can be difficult. 

I have not put much thought into which of the two I would personally prefer. On one hand, CD is simple and fits well with our current development cycle in practise, but on the other, dev-pending-release allows for further testing, better quality assurance, and fits better with semantic versioning. D-P-R does suffer from longer time-to-release with small patches (the third integer in the semantic version), and it does take more effort to manage it. Suggestions, critique, and ideas are all welcome.

**Comment by luciusmagn** [comment]
I agree

**Comment by bluelhf** [comment]
I wonder if [TBD](https://trunkbaseddevelopment.com/) would be possible?

**Comment by bluelhf** [comment]
For now, I've implemented simple TBD with branch protection on trunk: Small, pre-packaged commits are sent as pull requests via short-lived feature branches (which exist only between the creation of the PR and its merge), which can be merged if gradle tests run successfully. If this format works well, I plan to increase separation between Bukkit logic and the rest of BytePaper in order to allow extensive testing.
